AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tweeter Application - Serverless API

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        NODE_ENV: production
    Layers:
      - !Ref DependenciesLayer
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: tweeter-dependencies
      Description: Dependencies for Tweeter Lambda functions
      ContentUri: layer/
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain

  TweeterApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Name: tweeter-api
      Description: Tweeter REST API

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeter-Login
      Description: Authenticates a user with username and password, returns user profile and auth token
      CodeUri: dist/
      Handler: lambda/LoginLambda.handler
      Events:
        LoginApi:
          Type: Api
          Properties:
            RestApiId: !Ref TweeterApi
            Path: /login
            Method: POST

  LogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeter-Logout
      Description: Logs out a user by invalidating their authentication token
      CodeUri: dist/
      Handler: lambda/LogoutLambda.handler
      Events:
        LogoutApi:
          Type: Api
          Properties:
            RestApiId: !Ref TweeterApi
            Path: /logout
            Method: POST

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeter-Register
      Description: Registers a new user account with username, password, and profile information
      CodeUri: dist/
      Handler: lambda/RegisterLambda.handler
      Events:
        RegisterApi:
          Type: Api
          Properties:
            RestApiId: !Ref TweeterApi
            Path: /register
            Method: POST



  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeter-GetUser
      Description: Retrieves user profile information by username or alias
      CodeUri: dist/
      Handler: lambda/GetUserLambda.handler
      Events:
        GetUserApi:
          Type: Api
          Properties:
            RestApiId: !Ref TweeterApi
            Path: /user
            Method: POST

  FollowFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeter-Follow
      Description: Creates a follow relationship between the authenticated user and a target user
      CodeUri: dist/
      Handler: lambda/FollowLambda.handler
      Events:
        FollowApi:
          Type: Api
          Properties:
            RestApiId: !Ref TweeterApi
            Path: /follow
            Method: POST

  UnfollowFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeter-Unfollow
      Description: Removes a follow relationship between the authenticated user and a target user
      CodeUri: dist/
      Handler: lambda/UnfollowLambda.handler
      Events:
        UnfollowApi:
          Type: Api
          Properties:
            RestApiId: !Ref TweeterApi
            Path: /unfollow
            Method: POST

  GetFollowersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeter-GetFollowers
      Description: Retrieves a paginated list of users who follow the specified user
      CodeUri: dist/
      Handler: lambda/GetFollowersLambda.handler
      Events:
        GetFollowersApi:
          Type: Api
          Properties:
            RestApiId: !Ref TweeterApi
            Path: /followers
            Method: POST

  GetFolloweesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeter-GetFollowees
      Description: Retrieves a paginated list of users that the specified user follows
      CodeUri: dist/
      Handler: lambda/GetFolloweesLambda.handler
      Events:
        GetFolloweesApi:
          Type: Api
          Properties:
            RestApiId: !Ref TweeterApi
            Path: /followees
            Method: POST

  GetFollowerCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeter-GetFollowerCount
      Description: Returns the total number of followers for the specified user
      CodeUri: dist/
      Handler: lambda/GetFollowerCountLambda.handler
      Events:
        GetFollowerCountApi:
          Type: Api
          Properties:
            RestApiId: !Ref TweeterApi
            Path: /follower-count
            Method: POST

  GetFolloweeCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeter-GetFolloweeCount
      Description: Returns the total number of users that the specified user follows
      CodeUri: dist/
      Handler: lambda/GetFolloweeCountLambda.handler
      Events:
        GetFolloweeCountApi:
          Type: Api
          Properties:
            RestApiId: !Ref TweeterApi
            Path: /followee-count
            Method: POST

  GetIsFollowerStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeter-GetIsFollowerStatus
      Description: Checks whether the authenticated user is currently following a specified user
      CodeUri: dist/
      Handler: lambda/GetIsFollowerStatusLambda.handler
      Events:
        GetIsFollowerStatusApi:
          Type: Api
          Properties:
            RestApiId: !Ref TweeterApi
            Path: /is-follower
            Method: POST


  PostStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeter-PostStatus
      Description: Posts a new status update from the authenticated user
      CodeUri: dist/
      Handler: lambda/PostStatusLambda.handler
      Events:
        PostStatusApi:
          Type: Api
          Properties:
            RestApiId: !Ref TweeterApi
            Path: /status
            Method: POST

  GetFeedFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeter-GetFeed
      Description: Retrieves a paginated feed of status updates from users that the authenticated user follows
      CodeUri: dist/
      Handler: lambda/GetFeedLambda.handler
      Events:
        GetFeedApi:
          Type: Api
          Properties:
            RestApiId: !Ref TweeterApi
            Path: /feed
            Method: POST

  GetStoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeter-GetStory
      Description: Retrieves a paginated list of status updates posted by the specified user
      CodeUri: dist/
      Handler: lambda/GetStoryLambda.handler
      Events:
        GetStoryApi:
          Type: Api
          Properties:
            RestApiId: !Ref TweeterApi
            Path: /story
            Method: POST

Outputs:
  TweeterApiUrl:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${TweeterApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
    Export:
      Name: TweeterApiUrl

  TweeterApiId:
    Description: API Gateway ID
    Value: !Ref TweeterApi
    Export:
      Name: TweeterApiId

  Region:
    Description: Deployed Region
    Value: !Ref AWS::Region
